#!/bin/bash

sudo apt-get -y install build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion

sudo apt-get -y install libreadline-dev

curl -L get.rvm.io | bash -s stable
source "$HOME/.rvm/scripts/rvm"

#check whether RVM has been correctly installed
type rvm | head -1

#Install Ruby
rvm install 1.9.3
rvm use 1.9.3
rvm gemset create rails323
echo 'gem: --no-ri --no-rdoc' >> $HOME/.gemrc
echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function' >> $HOME/.bashrc
source ~/.bashrc
rvm use 1.9.3-p194@rails323 --default

#Install Rails
gem install rails sqlite3
echo 'Rails Instalation done'
ruby -v
rails -v

#Install Debugger
gem install ruby-debug19 -- --with-ruby-include=$rvm_path/src/ruby-1.9.3-p194/
gem install debugger -- --with-ruby-include=$rvm_path/src/ruby-1.9.3-p194/
