#!/bin/bash

# Adding RAILS for GEDIT
sudo add-apt-repository ppa:ubuntu-on-rails/ppa
sudo apt-get update
sudo apt-get install gedit-gmate
sudo apt-get install gedit-plugins

#Gedit TextMate
echo "GEdit"
mkdir $HOME/.fonts
wget -O $HOME/.fonts/MONACO.TTF http://www.webdevkungfu.com/files/MONACO.TTF
wget http://www.stambouliote.de/download/gedit_classbrowser-0.2.1.tar.gz
sudo tar xvzf gedit_classbrowser-0.2.1.tar.gz -C /usr/share/gedit-2/plugins/
rm gedit_classbrowser-0.2.1.tar.gz

echo .....................................................
wget http://grigio.org/files/darkmate.xml
echo "Open gedit and click on Edit -> Preferences -> Font & Colors. Then click on Add button and locate the download file(darkmate.xml)."
echo .....................................................
echo "Visit http://blog.sudobits.com/2011/04/02/textmate-for-ubuntu-linux/ TO INSTALL GEDIT"


