#!/bin/bash

#Install Notifier
sudo apt-get -y install libnotify-bin
gem install ZenTest
gem install autotest-notification
gem install autotest-rails
gem install redgreen

mkdir $HOME/Pictures/rails
wget -O $HOME/Pictures/rails/rails_fail.png http://algo.paluy.org/files/Tools/Notifier/rails_fail.png
wget -O $HOME/Pictures/rails/rails_ok.png http://algo.paluy.org/files/Tools/Notifier/rails_ok.png
wget -O $HOME/.autotest http://algo.paluy.org/files/Tools/Notifier/autotest
