#!/bin/bash

# Install Sublime
wget http://algo.paluy.org/files/Tools/SublimeText2/SublimeText2-32.tar.bz2
tar -jxvf SublimeText2-32.tar.bz2
rm SublimeText2-32.tar.bz2
wget -O SublimeText2/st2_icon_preview.png http://algo.paluy.org/files/Tools/SublimeText2/st2_icon_preview.png
sudo mv SublimeText2 /opt/
sudo ln -s /opt/SublimeText2/sublime_text /usr/local/bin/subl

# Create launcher
wget http://algo.paluy.org/files/Tools/SublimeText2/sublime.desktop
sudo mv sublime.desktop /usr/share/applications/
sudo chown -R root:root /usr/share/applications/sublime.desktop
sudo chmod -R +r /usr/share/applications/sublime.desktop

# Cucumber bundle
cd ~/.config/sublime-text-2/Packages
git clone git://github.com/sagework/cucumber-sublime2-bundle.git Cucumber

# Add awesomeness
######################################
# Will Bond’s Sublime Package Control
# visit: http://wbond.net/sublime_packages/package_control/installation
# After it has installed close and reopen Sublime Text and now your can press ctrl + shift + p  
# and you can now start installing some awesome packages by typing install and pressing enter.
#
# Nettuts + Fetch
# Prefixr  http://wbond.net/sublime_packages/prefixr
#
# Guard
# Rspec
# HAML
# Ruby Test https://github.com/maltize/sublime-text-2-ruby-tests

# Read more here: http://net.tutsplus.com/tutorials/tools-and-tips/sublime-text-2-tips-and-tricks/
# Unofficial Docs: http://readthedocs.org/docs/sublime-text-unofficial-documentation/en/latest/
