#!/bin/bash

#Install pathogen.vim
#mkdir -p ~/.vim/autoload ~/.vim/bundle
#curl -so ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/pathogen.vim

#Install vim-rails
#cd ~/.vim/bundle
#git clone git://github.com/tpope/vim-rails.git
#cd ~/

#Astrails VIM
cd ~/
git clone git://github.com/astrails/dotvim.git
ln -sfn dotvim .vim
ln -sfn dotvim/vimrc .vimrc
